CREATE TABLE Users (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  rating INT NOT NULL DEFAULT 0,
  confirmed BOOLEAN DEFAULT FALSE
);

CREATE TABLE Posts (
  id SERIAL PRIMARY KEY,
  body TEXT NOT NULL,
  rating INT DEFAULT 0,
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL,
  user_id INT REFERENCES Users ON DELETE CASCADE
);

CREATE TABLE Comments (
  id SERIAL PRIMARY KEY,
  comment TEXT NOT NULL,
  rating INT DEFAULT 0,
  user_id INT REFERENCES Users ON DELETE CASCADE,
  post_id INT REFERENCES Posts ON DELETE CASCADE
);

CREATE TABLE Posts_Ratings (
  id SERIAL PRIMARY KEY,
  rating INT NOT NULL,
  user_id INT REFERENCES Users ON DELETE CASCADE,
  post_id INT REFERENCES Posts ON DELETE CASCADE
);

CREATE TABLE Comments_Ratings (
  id SERIAL PRIMARY KEY,
  rating INT NOT NULL,
  user_id INT REFERENCES Users ON DELETE CASCADE,
  comment_id INT REFERENCES Comments ON DELETE CASCADE
);