const LOGIN_USER = 'LOGIN_USER';
const SHOW_ERRORS = 'SHOW_ERRORS';
const CLEAR_ERRORS = 'CLEAR_ERRORS';
const LOGOUT_USER = 'LOGOUT_USER';
const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';
const GET_LOCATION = 'GET_LOCATION';
const CLEAR_LOCATION = 'CLEAR_LOCATION';

export {
  LOGIN_USER,
  SHOW_ERRORS,
  CLEAR_ERRORS,
  LOGOUT_USER,
  START_LOADING,
  STOP_LOADING,
  GET_LOCATION,
  CLEAR_LOCATION
}