const LOGIN_USER = 'LOGIN_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const DELETE_USER = 'DELETE_USER';
const SHOW_ERRORS = 'SHOW_ERRORS';
const CLEAR_ERRORS = 'CLEAR_ERRORS';
const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';
const SET_LOCATION = 'SET_LOCATION';
const CLEAR_LOCATION = 'CLEAR_LOCATION';

export {
  LOGIN_USER,
  LOGOUT_USER,
  DELETE_USER,
  SHOW_ERRORS,
  CLEAR_ERRORS,
  START_LOADING,
  STOP_LOADING,
  SET_LOCATION,
  CLEAR_LOCATION
}